$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "https://maytetoscano.github.io/Bioclima_OGC/bblock/ogc.bioclima.policy.policy-alignment/schema.yaml"
title: "Indicator to Policy Alignment"

type: object
required: [indicator, alignments]
properties:
  indicator:
    type: string
    format: iri
  alignments:
    type: array
    minItems: 1
    items:
      type: object
      required: [target, relationship]
      properties:
        target:
          type: string
          format: iri
        relationship:
          type: string
          enum:
            - informs
            - measures-progress-on
            - triggers-action-for
            - supports-reporting-on
        evidenceStrength:
          type: string
          enum: [direct, indirect, contextual]
        justification:
          type: object
          required: [en]
          properties:
            en: { type: string }
            es: { type: string }
            zh: { type: string }
            ro: { type: string }
